// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
const datamap = {
	'Truck_7_axis': '3-004-006660-A-1-Truck 7-axis (r5) with Models',
};
// END EXTRA CODE

/**
 * @param {MxObject} appContext
 * @returns {Promise.<string>}
 */
export async function JavaScript_openCloud(appContext) {
	// BEGIN USER CODE
	let baseUrl = "http://shli6073:9000/3dviewer-testdat";
	// let baseUrl = "https://d2tic4q91nb3jq.cloudfront.net";

	const [fileType, ...rest] = appContext.get("CloudTestData").split('_')
	let modelName = rest.join('_').replace(/^_/i, '');
	
	let context = '';
	if(fileType === 'gltf'){
		context = `${baseUrl}/GLTF/${modelName}/${modelName}.gltf`;
	} else if (fileType === 'jt'){
		context = `${baseUrl}/JT/choice/${modelName}.jt`;
		if(modelName.indexOf('Shattered')>-1){
			modelName = modelName.replace(/^Shattered_/i, '');
			if(datamap[modelName]){
				modelName = datamap[modelName];
			}
			context = `${baseUrl}/JT/Shattered/${modelName}/${modelName}.jt`;
		}
	} else if (fileType === 'stl') {
		context = `${baseUrl}/stl/${modelName}.stl`;
	}
	return context;
	// END USER CODE
}
