// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
const DEBUG = true;
const PREFIX = '3dviewer::';

function log(msg, level='info', force=false){
	if(!DEBUG && !force){
		return;
	}
	
	let fn = console[level];
	if(fn){
		fn(`${PREFIX}${msg}`)
	}
}

const get = (selector, parent)=>{
	const root = parent || document;
	return root.querySelector(selector);
}
const hasClass = (el, className)=>{
	return el.classList.contains(className);
}
const toggleClass = (el, className) =>{
	const flag = hasClass(el, className);
	if (flag) {
		el.classList.remove(className);
	} else {
		el.classList.add(className);
	}
	return flag;
}

// END EXTRA CODE

/**
 * @param {MxObject} appContextEntity
 * @returns {Promise.<void>}
 */
export async function JavaScript_Initialize(appContextEntity) {
	// BEGIN USER CODE

	// add fullscreenchange lisener
	let isFullscreen = false;
	const handler = () => {
		
		isFullscreen = document.fullscreenElement !== null;
		console.log(`fullscreenchange changed: ${isFullscreen}`);
		// if (!isFullscreen) {
		// 	document.removeEventListener("fullscreenchange", handler);
		// }
		appContextEntity.set('FullScreenMode', isFullscreen);
	};
	document.addEventListener("fullscreenchange", handler);

	// END USER CODE
}
